### ISSUE TITLE
Include src in distribution

### ISSUE THREAD

**Issue by vojtasvoboda** [banthagroup/fslightbox#100]
After `npm install --save-dev fslightbox` I have `node_modules/fslightbox` with just `index.js`.

It would be nice to have also `node_modules/fslightbox/src` folder with `scss` and `js` files so I will be able to include these `scss` files in my build process. For example, I would be able to load only minimum lightbox without Video support, without YouTube support, without toolbar etc.

This `scss` folder could contain `settings.scss` file with variables for override, so I will be able to define my own background colors, arrows color etc.

This approach is able with [Bootstrap 4](https://getbootstrap.com/docs/4.3/getting-started/theming/#importing) or with [PhotoSwipe](https://github.com/dimsemenov/PhotoSwipe/tree/master/src/css).

**Comment by piotrzdziarski** [comment]
These changes would complicate the lightbox unduly. Coming across tens of files instead of just one file would be incongruous with the promise of an easy to use lightbox.
