### ISSUE TITLE
Change arrow icons

### ISSUE THREAD

**Issue by vojtasvoboda** [banthagroup/fslightbox#101]
Is there any way how to change the arrow's SVG and toolbar icons SVG? Thanks

**Comment by piotrzdziarski** [comment]
This feature is available in pro version, here is how to do this: 
[https://fslightbox.com/javascript/documentation/pro#svg](https://fslightbox.com/javascript/documentation/pro#svg)

**Comment by vojtasvoboda** [comment]
Thanks!
