### ISSUE TITLE
Autoplay parameter for Youtube

### ISSUE THREAD

**Issue by elijahworkz** [banthagroup/fslightbox#103]
How can I pass a parameter to auto play youtube video? When I attach it to the url in href - it gets stripped. Is there a data attribute that I can pass to force autoplay?

In Fancybox there are some default parameters (autoplay enabled by default) that are set unless there are parameters in the url

**Comment by banthagroup** [comment]
If you want to display customized YouTube iframe you can use custom sources: 
[https://fslightbox.com/javascript/documentation/basic#custom-sources](https://fslightbox.com/javascript/documentation/basic#custom-sources)

Example:
```
<a data-fslightbox="gallery" href="#custom-source">
   custom
</a>

 <iframe id="custom-source"
   frameborder="0"
   width="1920px"
   height="1080px"
   allow="autoplay; fullscreen"
   src="https://www.youtube.com/embed/xshEZzpS4CQ?autoplay=1">
</iframe>
```

**Comment by elijahworkz** [comment]
@banthagroup The problem is the autoplay forces video to start playing even if it's not the current slide. I think in fancybox they control videos to start/stop playing based on it's current position.

**Comment by banthagroup** [comment]
In pro version there is **onSlideChange** event. Use it and **onOpen** event and you can achieve what you want. Events description: [https://fslightbox.com/javascript/documentation/pro#events](https://fslightbox.com/javascript/documentation/pro#events)

Attach to them function which will do something like that:
```
function manageAutoplay(fsLightbox) {
     fsLightbox.elements.sources.forEach((source) => {
           
     });
}

fsLightboxInstances['gallery'].props.onOpen = manageAutoplay;
```

**Comment by banthagroup** [comment]
So you can do autoplaying manually. In pro version there is an event **onSlideChange**. With it and **onOpen** event you can achieve what you want. Pro version events description: [https://fslightbox.com/javascript/documentation/pro#events](https://fslightbox.com/javascript/documentation/pro#events)

Attach function which will do something like: 
```javascript
function manageAutoplay() {
   // sources array in elements object contains all sources of lightbox
   fsLightbox.elements.sources.forEach((source, index) => {
        if (source.tagName !== 'IFRAME') {
           return;
       }
       
       // stageIndexes object contains indexes of stage sources
       if (fsLightbox.stageIndexes.current === index) {
           // code that autoplays video
       } else {
            // code that stops video if playing
       } 
   });
}

fsLightbtoxInstances['gallery'].props.onOpen = manageAutoplay;
fsLightbtoxInstances['gallery'].props.onSlideChange = manageAutoplay;
```

But **onSlideChange** event is available only in full version.

**Comment by pettrushkov** [comment]
> If you want to display customized YouTube iframe you can use custom sources: https://fslightbox.com/javascript/documentation/basic#custom-sources
> 
> Example:
> 
> ```
> <a data-fslightbox="gallery" href="#custom-source">
>    custom
> </a>
> 
>  <iframe id="custom-source"
>    frameborder="0"
>    width="1920px"
>    height="1080px"
>    allow="autoplay; fullscreen"
>    src="https://www.youtube.com/embed/xshEZzpS4CQ?autoplay=1">
> </iframe>
> ```

hi, your code not working
https://codepen.io/pettrushkov/pen/jOYgVRP
