### ISSUE TITLE
Change the default font family

### ISSUE THREAD

**Issue by gui-com-pt** [banthagroup/fslightbox#105]
Hi,

I'm trying to change the default font family used because the Roboto is only used for this library on the website i'm working on and i wanted to avoid that extra request.

From what i understood the CSS styles are injected from JS. I'm developing a WP theme with Sage Roots and importing the library but i can't find any option in the ES module to change it.

Am i able to disable the injection of the CSS using JS? That way i may be able to use a variable in **Container.scss** to define the font-family and replace it, then i would import the SASS styles.

What do you think about it?

Thanks in advance!

**Comment by piotrzdziarski** [comment]
Just released new version without Roboto font - replaced it with available in CSS Helvetica.
