### ISSUE TITLE
Android - fsLightbox react pro issue, Android need duble click to exit fullscreen mode 

### ISSUE THREAD

**Issue by ikuska** [banthagroup/fslightbox#108]
Hey,
we have another problem with react fslightbox pro. 
Open image with fslighbox pro on Android device, tap fullscreen icon and next try to exit fullscreen mode. You need duble tap this icon to exit this mode.
Video with issue : 

https://www.youtube.com/watch?v=GDFuU6wJgKk

**Comment by banthagroup** [comment]
fixed in 1.5.0
