### ISSUE TITLE
Re-Init after ajax load

### ISSUE THREAD

**Issue by jesserosenfield** [banthagroup/fslightbox#110]
Hello! 

Thanks so much for this wonderful plugin. Amazing work!

Is there a way to re-initialize fslightbox on `[data-fslightbox]` elements after they've been loaded to the DOM dynamically. In my particular case I'm using a plugin called swup js https://swup.js.org

**Comment by msilight** [comment]
I have the same problem. I'm using swup but can't re-initialize fslighbox.

**Comment by AlexAntonyan** [comment]
refreshFsLightbox();

**Comment by piotrzdziarski** [comment]
Just use refreshFsLightbox after ajax load: [https://fslightbox.com/javascript/documentation/how-to-use#refreshing](https://fslightbox.com/javascript/documentation/how-to-use#refreshing
