### ISSUE TITLE
[FR] Is there any option to enable HTML5 Video 'autoplay'?

### ISSUE THREAD

**Issue by rommelmamedov** [banthagroup/fslightbox#113]
I use react verison of fslightbox.

**Comment by rommelmamedov** [comment]
# `Feature Request` 🙂

**Comment by banthagroup** [comment]
In 3.2.0 you can add autoplay parameter with custom attributes.

Add to video &lt;a&gt; tag **data-autoplay** attribute:
`
 <a data-fslightbox="gallery" data-autoplay href="video.mp4"></a>
`

**Comment by amitsarkerr** [comment]
Still, Autoplay on a video does not work
