### ISSUE TITLE
Add prop to specify alt tags like captions

### ISSUE THREAD

**Issue by dmorda** [banthagroup/fslightbox#116]
I'm building a website that requires good website accessibility and one of the big things is having good alt tags for images. Right now it seems the alt tag for an image in the slideshow is the URL to the image. 

Would it be possible to include a prop that allows me to specify the alt tags for images that are in the slideshow, similar to how I can do captions possibly?

**Comment by banthagroup** [comment]
Since 3.2.0 there are available custom attributes.
You can add alt using **data-** prefix.:
`
<a data-fslightbox="gallery" data-alt="Image description" href="img.jpg"></a>
`

**Comment by salientknight** [comment]
@banthagroup this is not an option when using the react code that accepts an array for image and caption. data-alt doesn't work nor does alt 

`<FsLightbox
        toggler={lightboxController.toggler}
        slideChangeAnimation="scale-in"
        sources={imageData}
        slide={lightboxController.slide}
        data-alt={[...imageAlt]}
        //showThumbsOnMount={true}
        captions={[...imageCaption]}
      />`
