### ISSUE TITLE
Add support for image srcset

### ISSUE THREAD

**Issue by pvonseth** [banthagroup/fslightbox#117]
Especially on mobile it would be a performance advantage if the Lightbox would supports the img srcset and thus reduces the loading time for the user.

**Comment by banthagroup** [comment]
Since 3.2.0 there are available custom attributes.
You can add srcset using **data-** prefix:
`
<a data-fslightbox="gallery" data-srcset="img/second.jpg 2x, img/third.jpg 3x" href="first.jpg"></a>
`
