### ISSUE TITLE
Option to disable inject styles into document?

### ISSUE THREAD

**Issue by DiemenDesign** [banthagroup/fslightbox#119]
Hi, firstly, thanks for a lightweight option to Fancybox, I'm looking at replacing Fancybox with this better alternative as I remove dependency of jQuery for front end users in the CMS I built (AuroraCMS).

I would have liked to use the Pro version, but I believe the licensing, even if purchased would restrict that, for multiple sites.

I would, however, like to be able to restyle some of the styles to suite client website themes. I had a quick look through the source, and the documentation, but couldn't find an option to turn off injecting the styling into the document.

Is this something we can have added for future releases, with an optional output when building the source to include a stylesheet?

I can of course simply remove the markup that's injected into the document, but I don't want to have to modify your code every time there's a release.

TIA

**Comment by piotrzdziarski** [comment]
Can't you just overwrite the styles you want to change?

**Comment by DiemenDesign** [comment]
Of course, but I don't want them injected into the DOM.
