### ISSUE TITLE
Is it possible to programmatically open image in lightbox?

### ISSUE THREAD

**Issue by DiemenDesign** [banthagroup/fslightbox#120]
I was wondering if it's possible to open images in the lightbox using script commands like:
````javascript
fsLightbox('<url to image>');
````
I figure the command would be different if this is possible. I'm hoping to bypass the ugly quick display to view larger images when clicking on the thumbnail images in elFinder.

**Comment by banthagroup** [comment]
You can do it the following way:
```
const lightbox = new FsLightbox();
lightbox.props.sources = ['<url to image>'];
lightbox.open();
```
