### ISSUE TITLE
Not works with some image urls

### ISSUE THREAD

**Issue by joaom182** [banthagroup/fslightbox#124]
I'm trying to render a gallery imagem from Google Cloud Storage, and when lightbox open, return "Invalid source".

**Example of image URL**
`https://storage.googleapis.com/sellers-pictures/f1305769-2965-43ba-ba30-cd7a8ce2a647.jpg`

<img width="841" alt="Screen Shot 2020-07-25 at 10 15 59" src="https://user-images.githubusercontent.com/3612098/88457804-da6ccd80-ce5f-11ea-890d-397ed462eb4c.png">

**Comment by ffd8** [comment]
Just ran into similar issue with a cloud bucket – could either be a CORS issue, or maybe you just need to specify it's an image, adding  ` data-type="image"` to the `<a>` tag...

**Comment by joaom182** [comment]
@ffd8 year i've confirmed, it's a CORS issue. But when i render inline `<img />` tag, the image is rendered. But when i open the light box, throw the CORS issues on console.

**Comment by joaom182** [comment]
@ffd8 i've found the solution.

Create a json file, ex: `storage-settings.json` with the content:
```json
[
  {
    "origin": ["*"],
    "method": ["GET", "OPTIONS"],
    "responseHeader": [
      "Origin",
      "Accept",
      "X-Requested-With",
      "Authorization",
      "Content-Type",
      "Content-Length",
      "Accept-Encoding",
      "X-CSRF-Token"
    ],
    "maxAgeSeconds": 1
  }
]
```

Apply this file to configure CORS on your bucket running the command:
```bash
gsutil cors set [PATH_TO_JSON_FILE] gs://[BUCKET_NAME]
```
