### ISSUE TITLE
 Not works with the localhost images URLS

### ISSUE THREAD

**Issue by Ekomunthe48** [banthagroup/fslightbox#127]
I'm trying render my image from my database and the Cors problem is gone but still not previewed the image in the lightbox

i'm use my localhost rest api

![image](https://user-images.githubusercontent.com/17869586/90211401-c7c03580-de1a-11ea-88b6-c67ec30e7328.png)

**Comment by banthagroup** [comment]
Lightbox caches detected types in local storage. Try clearing it and see if it works!

**Comment by Ekomunthe48** [comment]
Okay it work finally thank you :)
