### ISSUE TITLE
Question: Possible to specify/customize the Zoom increment?

### ISSUE THREAD

**Issue by jhogue** [banthagroup/fslightbox#130]
I am a Pro user and want to know if it is possible to increase the Zoom increment. Here is the way I am using it. 

HTML:
```
<a data-fslightbox="air-lightbox" data-type="image" data-caption="L. Baker 1903" href="/property-img/vintage-aerials-pvd/pvd-1903-unlabelled.jpg" role="button" aria-label="Link opens image in a larger pop-over">
  <img src="/property-img/vintage-aerials-pvd/pvd-1903-unlabelled.jpg" alt="" loading="eager">
</a>
```

Pretty simple. Only one working customization so far to the slideshow timing:
```
fsLightboxInstances['air-lightbox'].props.slideshowTime = 6000;
```

Thanks for any pointers.

**Comment by piotrzdziarski** [comment]
Customizable zoom increment was added in pro 3.3.0:
https://fslightbox.com/javascript/documentation/other-props#zoom-increment
