### ISSUE TITLE
Version 3.2.0+ breaks when using attributes like "style" or anything not pre-pended with `data`

### ISSUE THREAD

**Issue by LordZardeck** [banthagroup/fslightbox#131]
https://github.com/banthagroup/fslightbox/blob/master/src/index.js#L65 Looks like this introduced a regression. I have anchor elements with a `style` attribute, and it breaks, as it registers a `""` attribute, and when it tries to set it, it fails due to that not being a valid attribute name. This should be changed to ensure that the attribute is prefaced with `data` before registering it.

**Comment by tomnightingale-adtrak** [comment]
+1 - This also conflicts with `class` attributes too.

**Comment by sebastian-kopiczko** [comment]
> +1 - This also conflicts with `class` attributes too.

Same here, adding class attribute to the link cause error:
`Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '' is not a valid attribute name.`

**Comment by piotrzdziarski** [comment]
Fixed in 3.2.2
