### ISSUE TITLE
[Pro] Feature Request - Data option to disable zoom

### ISSUE THREAD

**Issue by tcpinski** [banthagroup/fslightbox#140]
Forgive me if there's already documentation on this but I couldn't find anything. Is there an option to disable zoom?

**Comment by cenda** [comment]
Hi @tcpinski, did you solve your problem? Is there any option to disable buttons from toolbar (except thumbs, this case is described in docs)? Thanks for your reply.

**Comment by clapczyn** [comment]
Hi @cenda and @tcpinski

Did you have any luck with this? I'm trying to use fslightbox for html content (I know this is not really the usecase) and it works almost the way I need it. 

I just need to disable zoom. I've tried to set zoomIncrement to 0 but that doesn't change anything. 

Any tips appreciated!
Thanks

**Comment by dmnkhhn** [comment]
Has this feature been removed? Setting this prop just doesn't to anything on the latest Pro version.
