### ISSUE TITLE
Unclear Pro license terms for use on public site.

### ISSUE THREAD

**Issue by garretwilson** [banthagroup/fslightbox#143]
I'm unclear how I'm supposed to use the Pro version once I purchase a license.

Your [plain JavaScript demo](https://fslightbox.com/javascript) for Pro says:

> As there is no way to protect js code on website Vanilla Javascript pro version demo is not available. 

Huh? But if I purchase and use the Pro version on my own website, it would be available via download (it would have to be to work in the browser!) just like the demo, right?

I also read the [license](https://fslightbox.com/licenses) terms:

> You cannot … offer the file downloaded directly or non-directly to any other third party (people, NGO's, companies).

But again, just using the Pro version on a public site would be definition be offering it to be downloaded by people, right?

I'm confused. Are you saying that we may not use the Pro version on a public website?

**Comment by piotrzdziarski** [comment]
A demo for the pro version is now available and the user license agreement was clarified.
