### ISSUE TITLE
Every time any lightbox is open it scrolls page to up

### ISSUE THREAD

**Issue by JayshreeMahajan** [banthagroup/fslightbox#145]
Hi,

Thanks for the library. It's great.
but I am having one issue that whenever any lightbox is opened it  scroll up page.
any solution for this

**Comment by jasmin92** [comment]
Any solution to this?

**Comment by ivqonsanada** [comment]
> Hi,
> 
> Thanks for the library. It's great.
> but I am having one issue that whenever any lightbox is opened it scroll up page.
> any solution for this

i have same issue, did you solve this problem?

**Comment by ivqonsanada** [comment]
> Any solution to this?
@jasmin92 

I just solve the problem by edit the source itself, at least its working as expected. 
you just need to search `fslightbox-open` in the script, delete the `overflow: hidden`, and it works like a charm

**Comment by roman-rr** [comment]
Hence, you can solve it without source editing: 
```css
.fslightbox-open {
  overflow: initial !important;
}
```
