### ISSUE TITLE
How to disable the loop? 

### ISSUE THREAD

**Issue by erickmonteiro** [banthagroup/fslightbox#171]
When opening fslightbox it runs the content in a loop, how do I make the last item not go back to the first one? I'm using the PRO version.

**Comment by grazielleanna** [comment]
Hi! I have this problem for. Did you find solution?

**Comment by erickmonteiro** [comment]
Unfortunately I couldn't solve it, I migrated to fancybox 4.

https://fancyapps.com/docs/ui/fancybox/react

**Comment by erickmonteiro** [comment]
> Hi! I have this problem for. Did you find solution?

Unfortunately I couldn't solve it, I migrated to fancybox 4.

https://fancyapps.com/docs/ui/fancybox/react
