### ISSUE TITLE
Is this project dead? Lots of issues and no support.

### ISSUE THREAD

**Issue by seandelaney** [banthagroup/fslightbox#202]

**Comment by seandelaney** [comment]
@antonatflow I also purchased. I've not heard a peep out of anyone belong to this project. Makes me very angry that they still take your money but offer no support and IMO the project is dead.

**Comment by j3ll3yfi5h** [comment]
Have a look at the commits – they're continuously making changes and improvements...

**Comment by antonatflow** [comment]
Thanks @j3ll3yfi5h, yes. Author has given me great support in the meantime. Can confirm @piotrzdziarski has started resolving some of the issues.

**Comment by j3ll3yfi5h** [comment]
Release notes here: https://fslightbox.com/javascript/release-notes
