### ISSUE TITLE
Cannot read properties of null (reading 'charAt')

### ISSUE THREAD

**Issue by Genaker** [banthagroup/fslightbox#205]
If you don't have **href** in any **a** tag your script doesn't work. 

fslightbox.js:1 Uncaught TypeError: Cannot read properties of null (reading 'charAt')
    at t (fslightbox.js:1:28028)
    at ae (fslightbox.js:1:28901)
    at Module.<anonymous> (fslightbox.js:1:30350)
    at n (fslightbox.js:1:358)
    at fslightbox.js:1:1157
    at fslightbox.js:1:1166
    at fslightbox.js:1:158
    at fslightbox.js:1:223

Fix - add exception;

o=e[t].getAttribute("href");fsLightboxInstances[n]||(fsLightboxInstances[n]=new FsLightbox);var r=null;"#"===**o**.charAt(0)?

you need check first if **o** is no null

**Comment by piotrzdziarski** [comment]
The issue was fixed in the 3.4.1 version of the basic edition and the 3.4.7 version of the pro edition.
A console warning is now thrown if any <a> element contains the "data-fslightbox" attribute without the "href" attribute.
