### ISSUE TITLE
Empty 'div' at the bottom of the page.

### ISSUE THREAD

**Issue by DepressiaGitHub** [banthagroup/fslightbox#206]
For each gallery library create empty div at the bottom of the page. And in the Chrome it have 17px height.
https://skr.sh/sIJdE8QOWXU

if i remove style='overflow: scroll;' all be good. But monkey patching is bad practices.

How i can fix it?

**Comment by piotrzdziarski** [comment]
The issue was fixed in the 3.4.1 version of the basic edition and 3.4.7 version of the pro edition.
