### ISSUE TITLE
How to load pictures encoded with base64

### ISSUE THREAD

**Issue by aleksygoroszko** [banthagroup/fslightbox#79]
I'd like to load picture not as URL strings, but as an encoded string, for example `data:image/jpeg;base64,[......]`. Is it possible in any way?
Thanks

**Comment by MKlblangenois** [comment]
Hi aleksygoroszko !

You can use base64 to display your image in FSLigthbox simply like that :

```
<a data-fslightbox href="data:image/jpeg;base64,[.....]">
   <img src="data:image/jpeg;base64,[.....]" />
</a>
```

Lightbox convert automatically your base64 in href into an image object 😀
