### ISSUE TITLE
sourceIndex doesnot work properly

### ISSUE THREAD

**Issue by sarbjeetsingh** [banthagroup/fslightbox#81]
Hi,
I have an image gallery. I am opening lightbox when the user clicks on any of the images and I am passing the Index of the images array to Lightbox. At first, it opens the Lightbox with the right image. But when I move images in the lightbox and close it then if I open it again it opens at the last image the where I closed the lightbox. So basically it is not updating the shouceIndex after closing the lightbox.

**Comment by piotrzdziarski** [comment]
I assume you are talking about React version, right? Can you show code?

**Comment by piotrzdziarski** [comment]
No response - closing.

**Comment by ttstauss** [comment]
I am currently facing the same issue. Everything else seems to function as expected. It doesn't seem like the sourceIndex is being updated when a user moves through images in the lightbox then closes.

I have it set up as explained [here](https://fslightbox.com/react/documentation/control-slide-number). I am using the fslightbox-react version.

Here is a code snippet of my set up:

```
import React, { useState } from "react"
import Img from "gatsby-image/withIEPolyfill"
import FsLightbox from "fslightbox-react"

const WorkGallery = ({ gallery }) => {
  const [lightboxController, setLightboxController] = useState({
    toggler: false,
    sourceIndex: 0,
  })
  const images = gallery.map(({ image }) => {
    return image.fluid.src
  })

  function openLightboxOnSlide(index) {
    setLightboxController({
      toggler: !lightboxController.toggler,
      sourceIndex: index,
    })
  }

  return (
    <div>
      <div className="work-gallery">
        {gallery.map(({ image }, index) => {

          return (
            <div
              key={image.id}
              onClick={e => {
                e.preventDefault()
                openLightboxOnSlide(index)
              }}
              onKeyPress={e => {
                e.preventDefault()
                openLightboxOnSlide(index)
              }}
              role="button"
              tabIndex={index}
            >
              <Img
                objectFit="cover"
                fluid={image.fluid}
                alt={image.title}
              />
            </div>
          )
        })}
      </div>
      <FsLightbox
        toggler={lightboxController.toggler}
        sources={images}
        sourceIndex={lightboxController.sourceIndex}
      />
    </div>
  )
}

export default WorkGallery
```
