### ISSUE TITLE
Can´t open with only 1 image

### ISSUE THREAD

**Issue by lukastrkan** [banthagroup/fslightbox#97]
Hi,
I am facing issue, that I can´t open fslightbox when there is only 1 image in it. 
Multiple images works fine.

Html code:
https://pastebin.com/e8rBJeKz

Error code: 
`fslightbox.js:1 Uncaught TypeError: n.setSlideNumber is not a function
    at Object.i.open (fslightbox.js:1)
    at window.FsLightbox.open (fslightbox.js:1)
    at HTMLAnchorElement.e.<computed>.onclick (fslightbox.js:1)
i.open @ fslightbox.js:1
open @ fslightbox.js:1
e.<computed>.onclick @ fslightbox.js:1
`

Thanks for any help

**Comment by piotrzdziarski** [comment]
Released new version with fix for this issue!
