### ISSUE TITLE
Broad CSS properties messing with CSS frameworks

### ISSUE THREAD

**Issue by Alex-Hay** [banthagroup/fslightbox#98]
Hi there,

Love what you've done with this, you've made a really great lightbox! One small nit-pick is that those of us using [TailwindCSS](https://tailwindcss.com/) are running into a few css conflicts (primarily .hidden). It'd be great it some of the targeted css properties could have a narrower scope and preferably load in from an external stylesheet.

Thanks for your hard work!
Alex

**Comment by piotrzdziarski** [comment]
Hello,

I'm glad you like it! 
Where do you exactly run into conflict with .hidden?

**Comment by edwardjosephbennett** [comment]
As TailwindCSS is a utility first framework it contains a class to hide elements by applying `.hidden`. As your classes are added to the head of the document, this has more specificity than the ones defined by and used in tailwind, causing elements to be hidden on the page.

I've created a merge request with a fix, that hopefully should resolve the issue. Sorry if I've done it wrong or I haven't fixed all issues (I couldn't find any docs on how to submit the fix).

See #104

**Comment by SergeyKons** [comment]
Hi! Thanks for resolving this problem. Can you make release with this fix?

**Comment by piotrzdziarski** [comment]
Released new version with this fix.
